name: gestion_presence_2
description: "Application Flutter de gestion de présence avec backend Node.js"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI et design
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0

  # Navigation
  go_router: ^14.2.7

  # Gestion d'état
  flutter_riverpod: ^2.5.1

  # QR codes et scanner
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1

  # Fichiers et Excel
  file_picker: ^8.1.2
  excel: ^4.0.4

  # Communication HTTP
  http: ^1.2.2

  # Stockage local pour le token JWT
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
